# Generated by Django 3.0.2 on 2020-04-15 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myclass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('disc', models.CharField(max_length=1000)),
                ('pic', models.ImageField(upload_to='static/')),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Medical', 'Medical'), ('DailyE', 'DailyE')], default='Grocery', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=50)),
                ('shop_name', models.CharField(max_length=20)),
                ('shop_pic', models.ImageField(upload_to='static/')),
                ('shop_disc', models.CharField(max_length=100)),
                ('shop_add', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('contact', models.IntegerField(default='')),
                ('delivery', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Medical', 'Medical'), ('DailyE', 'DailyE')], default='Grocery', max_length=20)),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='oredr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default='0')),
                ('quantity', models.CharField(default='', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
