# Generated by Django 3.0.2 on 2020-04-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20200415_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_disc', models.CharField(max_length=100)),
                ('prod_price', models.FloatField()),
                ('category', models.CharField(choices=[('Grocery', 'Grocery'), ('Medical', 'Medical'), ('DailyE', 'DailyE')], default='Grocery', max_length=20)),
                ('prod_img', models.ImageField(upload_to='static/prod/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.shop')),
            ],
        ),
    ]
