# Generated by Django 3.0.2 on 2020-04-21 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0002_cart_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
