# Generated by Django 3.0.2 on 2020-04-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20200417_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
