# Generated by Django 3.0.2 on 2020-04-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'COD'), ('Online', 'Online')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Dispatched', 'Dispatched'), ('Denied', 'Denied'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
