# Generated by Django 3.0.2 on 2020-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20200421_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('sub', models.CharField(blank=True, max_length=30)),
                ('msg', models.TextField()),
            ],
        ),
    ]
