# Generated by Django 3.0.2 on 2020-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_myblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(default='Bareilly', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='loclity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
