# Generated by Django 3.0.2 on 2020-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auto_20200430_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_pic',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
