# Generated by Django 3.0.2 on 2020-05-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_auto_20200430_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
