# Generated by Django 3.0.2 on 2020-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_auto_20200508_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
