# Generated by Django 3.0.2 on 2020-09-30 08:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_auto_20200930_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
