# Generated by Django 3.0.2 on 2020-10-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_products_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='myblog',
            name='slug',
            field=models.SlugField(default=' ', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='category_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.shop')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='category_n',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.category_prod'),
        ),
    ]
