# Generated by Django 3.0.2 on 2020-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_auto_20201002_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
